// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dblqpqylmuslybhskjqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRibHFwcXlsbXVzbHliaHNranF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTc4NzIsImV4cCI6MjA2NzA5Mzg3Mn0.NCghO7c1Iy-lOsU6ntDYML2HDgLEv4aZj1SnwuIgibk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});