// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urjmzfmzzfpkxlqhanlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyam16Zm16emZwa3hscWhhbmx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDMzOTMsImV4cCI6MjA2NjM3OTM5M30.GnQ9AJvXMUYWt29PniWKSLGJx3DbZq6lHE_hE0zift4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});